-- 用户表初始化脚本
CREATE TABLE T_USER (
    TID BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    USER_CODE VARCHAR(50) NOT NULL COMMENT '用户账号',
    USER_NAME VARCHAR(100) NOT NULL COMMENT '用户姓名',
    BIRTH_DATE DATE COMMENT '出生日期',
    GENDER VARCHAR(10) COMMENT '性别：男、女',
    NATION VARCHAR(50) COMMENT '民族',
    MOBILE VARCHAR(20) COMMENT '手机号',
    EMAIL VARCHAR(100) COMMENT '邮箱',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (TID),
    UNIQUE KEY UK_USER_CODE (USER_CODE),
    KEY IDX_USER_NAME (USER_NAME),
    KEY IDX_MOBILE (MOBILE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';

-- 插入测试数据
INSERT INTO T_USER (USER_CODE, USER_NAME, BIRTH_DATE, GENDER, NATION, MOBILE, EMAIL) VALUES
('admin', '管理员', '1990-01-01', '男', '汉族', '13800138000', 'admin@example.com'),
('user001', '张三', '1985-05-15', '男', '汉族', '13800138001', 'zhangsan@example.com'),
('user002', '李四', '1992-08-20', '女', '汉族', '13800138002', 'lisi@example.com'),
('user003', '王五', '1988-03-12', '男', '汉族', '13800138003', 'wangwu@example.com'),
('user004', '赵六', '1995-11-08', '女', '汉族', '13800138004', 'zhaoliu@example.com');
