-- 部门表初始化脚本
CREATE TABLE T_DEPARTMENT (
    TID BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    DEPT_CODE VARCHAR(50) NOT NULL COMMENT '部门编号',
    DEPT_NAME VARCHAR(100) NOT NULL COMMENT '部门名称',
    CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (TID),
    UNIQUE KEY UK_DEPT_CODE (DEPT_CODE),
    KEY IDX_DEPT_NAME (DEPT_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='部门表';

-- 插入测试数据
INSERT INTO T_DEPARTMENT (DEPT_CODE, DEPT_NAME) VALUES
('TECH', '技术部'),
('SALES', '销售部'),
('HR', '人力资源部');

-- 为用户表添加部门ID字段
ALTER TABLE T_USER ADD COLUMN DEPT_ID BIGINT COMMENT '所属部门ID';
ALTER TABLE T_USER ADD KEY IDX_DEPT_ID (DEPT_ID);

-- 更新现有用户的部门信息
UPDATE T_USER SET DEPT_ID = 1 WHERE USER_CODE IN ('admin', 'user001');
UPDATE T_USER SET DEPT_ID = 2 WHERE USER_CODE = 'user002';
UPDATE T_USER SET DEPT_ID = 3 WHERE USER_CODE IN ('user003', 'user004');
